### ISSUE TITLE
bug: /client not available

### ISSUE THREAD

**Issue by sinux-l5d** [WantGuns/bin#7]
Hello,

I just installed bin and I like it so far :D. I noticed an incoherence : the man-like page tells that you can download the client at `/client`, but I get the message `Unable to find entity 'client'` (try https://basedbin.fly.dev/client).

I installed bin with docker(-compose).

For now I just copied/pasted the client in the upload directory.

**Comment by WantGuns** [comment]
Hey !

Thanks for the feedback. I am aware of the /client incoherence. Since this entire project is shipped in a single binary, I assumed people would not want to forcefully carry the `client` alongside the binary.
It was intended for people to add `client` themselves if they wanted it. 
But I recognize the fault here, the man text is misleading, and I wouldn't want to put "bin.wantguns.dev/client" as the default client for everyone who selfhosts this.

I think its better to add the `client` to the binary. You can expect it very soon !

**Comment by sinux-l5d** [comment]
The design is good : I actually needed to update your client to add auth for my instance.
So maybe you just need to mention that in the readme and remove `/client` from the man text?

**Comment by WantGuns** [comment]
Huh, okay will do that then !

**Comment by WantGuns** [comment]
> I mean, shipping the client might be a bad idea if people wants to tweak it themselves. Maybe an env variable could disable it

Yup, was thinking of something similar
